### ISSUE TITLE
Not getting images neither iframe

### ISSUE THREAD

**Issue by Chomikmarkus** [swagkarna/Nivistealer#7]
Cannot get images tried google chrome and duckgo browsers, iframe is not opened neither video buttons are active
![Screenshot_20220315-224338](https://user-images.githubusercontent.com/92059377/158469270-caef3ee5-bd51-4ed5-93ad-c69381a03a26.png)
![Screenshot_20220315-223943](https://user-images.githubusercontent.com/92059377/158469274-8a10c8be-02ac-4987-a605-8014e8a8ef1c.png)

**Comment by Chomikmarkus** [comment]
With flask I'm getting error like this
e
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/__init__.py)
root@vps168451:/var/www/html/chat/python_flask# pip3 install itsdangerous
/usr/lib/python3/dist-packages/secretstorage/dhcrypto.py:15: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
/usr/lib/python3/dist-packages/secretstorage/util.py:19: CryptographyDeprecationWarning: int_from_bytes is deprecated, use int.from_bytes instead
  from cryptography.utils import int_from_bytes
Requirement already satisfied: itsdangerous in /usr/local/lib/python3.8/dist-packages (2.1.1)
root@vps168451:/var/www/html/chat/python_flask# python3 nivistealer.py
Traceback (most recent call last):
  File "nivistealer.py", line 2, in <module>
    from flask import Flask, render_template, url_for, request, jsonify,Response
  File "/usr/local/lib/python3.8/dist-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/usr/local/lib/python3.8/dist-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/usr/local/lib/python3.8/dist-packages/itsdangerous/__init__.py)
root@vps168451:/var/www/html/chat/python_flask# l

**Comment by Chomikmarkus** [comment]
Works with reality but not on vps, is there any permissions what should be changed?

**Comment by Chomikmarkus** [comment]
System i use is Ubuntu 20.04 vps machine ssl installed from letsencrypt and apache! I got flask to work 
https://www.google.com/amp/s/itsmycode.com/importerror-cannot-import-name-json-from-itsdangerous/amp/
But there is still issues grabbing front camera
